using Microsoft.EntityFrameworkCore; // Para ExecuteSqlRawAsync

namespace GestionPedidos.Data; // Namespace de la capa de datos

// "Migración manual": agrega a una base EXISTENTE las tablas y columnas nuevas, SIN borrar datos.
// Cada instrucción usa IF NOT EXISTS, así que se puede ejecutar en cada arranque sin problema (si ya está, no hace nada).
// Los tipos de columna son los mismos que crearía Entity Framework para PostgreSQL.
public static class ActualizacionesBase // Clase estática de ayuda
{ // Inicio de la clase
    // Versión 3: productos, renglones de pedido, movimientos de stock, descuento del pedido y consentimiento de emails
    private const string Version3 = """
        ALTER TABLE "Pedidos" ADD COLUMN IF NOT EXISTS "DescuentoPorcentaje" numeric(5,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Clientes" ADD COLUMN IF NOT EXISTS "NotificarPorEmail" boolean NOT NULL DEFAULT FALSE;

        CREATE TABLE IF NOT EXISTS "Productos" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Codigo" character varying(30) NOT NULL,
            "Nombre" character varying(150) NOT NULL,
            "Precio" numeric(12,2) NOT NULL,
            "Stock" integer NOT NULL,
            "StockMinimo" integer NOT NULL,
            "Activo" boolean NOT NULL,
            CONSTRAINT "PK_Productos" PRIMARY KEY ("Id")
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Productos_Codigo" ON "Productos" ("Codigo");

        CREATE TABLE IF NOT EXISTS "PedidoItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "PedidoId" integer NOT NULL,
            "ProductoId" integer NOT NULL,
            "ProductoNombre" character varying(150) NOT NULL,
            "Cantidad" integer NOT NULL,
            "PrecioUnitario" numeric(12,2) NOT NULL,
            "DescuentoPorcentaje" numeric(5,2) NOT NULL,
            CONSTRAINT "PK_PedidoItems" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_PedidoItems_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_PedidoItems_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT
        );
        CREATE INDEX IF NOT EXISTS "IX_PedidoItems_PedidoId" ON "PedidoItems" ("PedidoId");
        CREATE INDEX IF NOT EXISTS "IX_PedidoItems_ProductoId" ON "PedidoItems" ("ProductoId");

        CREATE TABLE IF NOT EXISTS "MovimientosStock" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "ProductoId" integer NOT NULL,
            "Fecha" timestamp with time zone NOT NULL,
            "Tipo" character varying(20) NOT NULL,
            "Cantidad" integer NOT NULL,
            "StockResultante" integer NOT NULL,
            "PedidoId" integer NULL,
            "Usuario" character varying(150) NOT NULL,
            "Motivo" character varying(300) NULL,
            CONSTRAINT "PK_MovimientosStock" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_MovimientosStock_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_MovimientosStock_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE SET NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_MovimientosStock_PedidoId" ON "MovimientosStock" ("PedidoId");
        CREATE INDEX IF NOT EXISTS "IX_MovimientosStock_ProductoId" ON "MovimientosStock" ("ProductoId");
        """; // Fin del SQL (las comillas triples permiten escribir varias líneas)

    // Versión 4 (etapa 2): fecha de entrega + evento de Google Calendar en el pedido, archivos en Google Drive y conexión con Google
    private const string Version4 = """
        ALTER TABLE "Pedidos" ADD COLUMN IF NOT EXISTS "FechaEntrega" date NULL;
        ALTER TABLE "Pedidos" ADD COLUMN IF NOT EXISTS "CalendarioEventoId" character varying(200) NULL;

        CREATE TABLE IF NOT EXISTS "ArchivosPedido" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "PedidoId" integer NOT NULL,
            "DriveId" character varying(200) NOT NULL,
            "Nombre" character varying(255) NOT NULL,
            "TipoMime" character varying(150) NOT NULL,
            "Tamano" bigint NOT NULL,
            "Fecha" timestamp with time zone NOT NULL,
            "Usuario" character varying(150) NOT NULL,
            CONSTRAINT "PK_ArchivosPedido" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_ArchivosPedido_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE
        );
        CREATE INDEX IF NOT EXISTS "IX_ArchivosPedido_PedidoId" ON "ArchivosPedido" ("PedidoId");

        CREATE TABLE IF NOT EXISTS "IntegracionesGoogle" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Email" character varying(150) NOT NULL,
            "RefreshTokenCifrado" text NOT NULL,
            "CarpetaDriveId" character varying(200) NULL,
            "FechaConexion" timestamp with time zone NOT NULL,
            "ConectadoPor" character varying(150) NOT NULL,
            "UltimoError" character varying(500) NULL,
            CONSTRAINT "PK_IntegracionesGoogle" PRIMARY KEY ("Id")
        );
        """; // Fin del SQL de la versión 4

    // Versión 5: invitaciones de usuarios por email
    private const string Version5 = """
        ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS "InvitacionPendiente" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS "InvitadoPor" character varying(150) NULL;
        """; // Fin del SQL de la versión 5

    public static async Task AplicarAsync(AppDbContext db) // Se llama al arrancar, después de EnsureCreated
    { // Inicio del método
        await db.Database.ExecuteSqlRawAsync(Version3); // Versión 3: productos y stock
        await db.Database.ExecuteSqlRawAsync(Version4); // Versión 4: Google Drive y Calendar
        await db.Database.ExecuteSqlRawAsync(Version5); // Versión 5: invitaciones
    } // Fin del método
} // Fin de la clase
