using Microsoft.EntityFrameworkCore; // Para ExecuteSqlRawAsync

namespace GestionPedidos.Data; // Namespace de la capa de datos

// "Migración manual": agrega a una base EXISTENTE las tablas y columnas nuevas, SIN borrar datos.
// Cada instrucción usa IF NOT EXISTS, así que se puede ejecutar en cada arranque sin problema (si ya está, no hace nada).
// Los tipos de columna son los mismos que crearía Entity Framework para PostgreSQL.
public static class ActualizacionesBase // Clase estática de ayuda
{ // Inicio de la clase
    // Versión 3: productos, renglones de pedido, movimientos de stock, descuento del pedido y consentimiento de emails
    private const string Version3 = """
        ALTER TABLE "Pedidos" ADD COLUMN IF NOT EXISTS "DescuentoPorcentaje" numeric(5,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Clientes" ADD COLUMN IF NOT EXISTS "NotificarPorEmail" boolean NOT NULL DEFAULT FALSE;

        CREATE TABLE IF NOT EXISTS "Productos" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Codigo" character varying(30) NOT NULL,
            "Nombre" character varying(150) NOT NULL,
            "Precio" numeric(12,2) NOT NULL,
            "Stock" integer NOT NULL,
            "StockMinimo" integer NOT NULL,
            "Activo" boolean NOT NULL,
            CONSTRAINT "PK_Productos" PRIMARY KEY ("Id")
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Productos_Codigo" ON "Productos" ("Codigo");

        CREATE TABLE IF NOT EXISTS "PedidoItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "PedidoId" integer NOT NULL,
            "ProductoId" integer NOT NULL,
            "ProductoNombre" character varying(150) NOT NULL,
            "Cantidad" integer NOT NULL,
            "PrecioUnitario" numeric(12,2) NOT NULL,
            "DescuentoPorcentaje" numeric(5,2) NOT NULL,
            CONSTRAINT "PK_PedidoItems" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_PedidoItems_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_PedidoItems_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT
        );
        CREATE INDEX IF NOT EXISTS "IX_PedidoItems_PedidoId" ON "PedidoItems" ("PedidoId");
        CREATE INDEX IF NOT EXISTS "IX_PedidoItems_ProductoId" ON "PedidoItems" ("ProductoId");

        CREATE TABLE IF NOT EXISTS "MovimientosStock" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "ProductoId" integer NOT NULL,
            "Fecha" timestamp with time zone NOT NULL,
            "Tipo" character varying(20) NOT NULL,
            "Cantidad" integer NOT NULL,
            "StockResultante" integer NOT NULL,
            "PedidoId" integer NULL,
            "Usuario" character varying(150) NOT NULL,
            "Motivo" character varying(300) NULL,
            CONSTRAINT "PK_MovimientosStock" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_MovimientosStock_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_MovimientosStock_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE SET NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_MovimientosStock_PedidoId" ON "MovimientosStock" ("PedidoId");
        CREATE INDEX IF NOT EXISTS "IX_MovimientosStock_ProductoId" ON "MovimientosStock" ("ProductoId");
        """; // Fin del SQL (las comillas triples permiten escribir varias líneas)

    public static async Task AplicarAsync(AppDbContext db) // Se llama al arrancar, después de EnsureCreated
        => await db.Database.ExecuteSqlRawAsync(Version3); // Ejecuta todas las instrucciones juntas
} // Fin de la clase
